ALTER TABLE public.books
ADD COLUMN badge VARCHAR(20) NOT NULL DEFAULT 'NEW',
ADD COLUMN average_rating NUMERIC(2,1) NOT NULL DEFAULT 0.0,
ADD COLUMN review_count BIGINT NOT NULL DEFAULT 0,
ADD COLUMN sold_copies BIGINT NOT NULL DEFAULT 0;