spring.config.import=optional:file:.env[.properties]

spring.application.name=ebook-reader
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

ebook-reader.app.jwtSecret=${JWT_SECRET}
ebook-reader.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
ebook-reader.app.jwtCookieName=${JWT_COOKIE_NAME}
ebook-reader.app.jwtRefreshCookieName=${JWT_REFRESH_COOKIE_NAME}
ebook-reader.app.jwtRefreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}

# Reset Password
ebook-reader.app.passwordResetTokenExpirationMs=${PASSWORD_RESET_TOKEN_EXPIRATION_MS}
# For test RP
#ebook-reader.app.passwordResetTokenExpirationMs=300000
## For test
#ebook-reader.app.jwtExpirationMs=60000
#ebook-reader.app.jwtRefreshExpirationMs=180000

# S3 supabase
ebook-reader.app.s3.endpointUrl=${S3_ENDPOINT_URL}
ebook-reader.app.s3.region=${S3_REGION}
ebook-reader.app.s3.accessKey=${S3_ACCESS_KEY}
ebook-reader.app.s3.secretKey=${S3_SECRET_KEY}
ebook-reader.app.s3.public.bucketName=${S3_PUBLIC_BUCKET_NAME}
ebook-reader.app.s3.private.bucketName=${S3_PRIVATE_BUCKET_NAME}
ebook-reader.app.s3.publicBaseUrl=${S3_PUBLIC_BASE_URL}
ebook-reader.app.s3.presigned-url-expiry-minutes=${S3_PRESIGNED_URL_EXPIRY_MINUTES}
## For test
#ebook-reader.app.s3.presigned-url-expiry-minutes=5

# Multipart file upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2MB

# VNPay
vnpay.tmnCode=${VNPAY_TMN_CODE}
vnpay.hashSecret=${VNPAY_HASH_SECRET}
vnpay.payUrl=${VNPAY_PAY_URL}
vnpay.returnUrl=${VNPAY_RETURN_URL}

# MoMo
momo.partnerCode=${MOMO_PARTNER_CODE}
momo.accessKey=${MOMO_ACCESS_KEY}
momo.secretKey=${MOMO_SECRET_KEY}
momo.payUrl=${MOMO_PAY_URL}
momo.redirectUrl=${MOMO_REDIRECT_URL}
momo.ipnUrl=${MOMO_IPN_URL}
momo.requestType=${MOMO_REQUEST_TYPE}

## Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##
app.frontend-url=${FRONTEND_URL}
app.mail.from=${MAIL_FROM}

spring.profiles.active=dev,mock-payment