spring.application.name=ebook-reader

spring.datasource.url=jdbc:postgresql://db.xkgcyjieubhrjokgxqrx.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=8D2TBtj9b7DFR2Mf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false

spring.hibernate.jpa.show-sql=true
spring.hibernate.jpa.properties.ddl-auto=none

