flyway.user=postgres.xkgcyjieubhrjokgxqrx
flyway.password=cUE1uJNZFQK6N9V1
flyway.schemas=public
flyway.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
flyway.locations=filesystem:src/main/resources/db/migration